"""Apply colour and text-style design tokens to generated Word resumes."""

from __future__ import annotations

from pathlib import Path
from tempfile import NamedTemporaryFile
import re
from typing import Mapping
from zipfile import ZIP_DEFLATED, ZipFile

from lxml import etree

from design_tokens import DesignTokens, TextStyle


WORD_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
DRAWING_NS = "http://schemas.openxmlformats.org/drawingml/2006/main"
NS = {"w": WORD_NS, "a": DRAWING_NS}
THEME_PART = "word/theme/theme1.xml"

# These are the direct-formatting colours in the fixed Word layout. Mapping
# them at build time preserves the layout while making the public resume use
# the same semantic palette as the website.
DIRECT_COLOUR_TOKENS = {
    "18324A": "green",
    "1F2933": "ink",
    "5E6C78": "muted",
    "7A8793": "line_dark",
    "FFFFFF": "white",
}
DIRECT_FILL_TOKENS = {
    "18324A": "green",
    "F7F9FB": "paper",
}
THEME_COLOUR_TOKENS = {
    "dk1": "ink",
    "lt1": "white",
    "dk2": "green",
    "lt2": "paper_deep",
    "accent1": "accent",
    "accent2": "accent_hover",
    "accent3": "green",
    "accent4": "palette.turquoise_metallic",
    "accent5": "palette.stratos_blue_metallic",
    "accent6": "accent_dark",
    "hlink": "palette.bright_blue_metallic",
    "folHlink": "palette.royal_blue_metallic",
}

RESUME_TEXT_STYLE_BY_TAG = {
    "CONTACT_NAME": "resume.name",
    "CONTACT_PHONE": "resume.contact",
    "CONTACT_EMAIL": "resume.contact",
    "CONTACT_WEBSITE": "resume.contact",
    "CONTACT_LOCATION": "resume.metadata",
    "PROFILE_SUMMARY": "resume.body",
    "EDU_INSTITUTION": "resume.organization",
    "EDU_DEGREE": "resume.body",
    "EDU_DATES": "resume.metadata",
    "EDU_BULLET1": "resume.body",
    "EDU2_INSTITUTION": "resume.organization",
    "EDU2_DEGREE": "resume.body",
    "EDU2_DATES": "resume.metadata",
    "EDU2_BULLET1": "resume.body",
    "PAGE2_NAME": "resume.page_name",
    "PAGE2_WEBSITE": "resume.page_meta",
    "TECH_CAD": "resume.body",
    "TECH_ELECTRICAL": "resume.body",
    "TECH_DATA": "resume.body",
    "TECH_ENGINEERING_SOFTWARE": "resume.body",
    "TECH_FABRICATION": "resume.body",
    "PORTFOLIO_URL": "resume.project_context",
}

# The template has fixed, semantic slots. Keeping the mapping generated by
# section and slot makes it easy to change capacity without falling back to
# layout-specific formatting or person-specific field names.
for _slot in (1, 2):
    RESUME_TEXT_STYLE_BY_TAG[f"EXP{_slot}_TITLE"] = "resume.position_title"
    RESUME_TEXT_STYLE_BY_TAG[f"EXP{_slot}_META"] = "resume.detail"
    RESUME_TEXT_STYLE_BY_TAG[f"EXP{_slot}_DATES"] = "resume.metadata"
    for _bullet in (1, 2, 3, 4):
        RESUME_TEXT_STYLE_BY_TAG[f"EXP{_slot}_BULLET{_bullet}"] = "resume.body"

for _prefix, _slots, _title_style in (
    ("LEAD", (1, 2), "resume.position_title"),
    ("COMM", (1,), "resume.position_title"),
    ("RECOG", (1, 2, 3), "resume.award"),
):
    for _slot in _slots:
        RESUME_TEXT_STYLE_BY_TAG[f"{_prefix}{_slot}_TITLE"] = _title_style
        RESUME_TEXT_STYLE_BY_TAG[f"{_prefix}{_slot}_META"] = "resume.detail"
        RESUME_TEXT_STYLE_BY_TAG[f"{_prefix}{_slot}_DATES"] = "resume.metadata"
        RESUME_TEXT_STYLE_BY_TAG[f"{_prefix}{_slot}_BULLET1"] = "resume.body"

for _slot in (1, 2, 3, 4, 5, 6):
    RESUME_TEXT_STYLE_BY_TAG[f"GENERAL_SKILL_{_slot}"] = "resume.skill"

for _slot in (1, 2, 3, 4):
    RESUME_TEXT_STYLE_BY_TAG[f"PROJECT{_slot}_TITLE"] = "resume.project_title"
    RESUME_TEXT_STYLE_BY_TAG[f"PROJECT{_slot}_META"] = "resume.project_tool"
    RESUME_TEXT_STYLE_BY_TAG[f"PROJECT{_slot}_DATES"] = "resume.page_meta"
    for _bullet in (1, 2, 3, 4):
        RESUME_TEXT_STYLE_BY_TAG[f"PROJECT{_slot}_BULLET{_bullet}"] = "resume.body"
STATIC_RESUME_TEXT_STYLES = {
    "EDUCATION": "resume.section_heading",
    "EXPERIENCE": "resume.section_heading",
    "LEADERSHIP": "resume.section_heading",
    "COMMUNITY INVOLVEMENT": "resume.section_heading",
    "CORE CAPABILITIES": "resume.section_heading",
    "RECOGNITION": "resume.section_heading",
    "SELECTED PROJECT PORTFOLIO": "resume.section_heading",
    "TECHNICAL SKILLS": "resume.section_heading",
    "PROJECT PORTFOLIO": "resume.page_heading",
}
POINT_VALUE = re.compile(r"^(\d+(?:\.\d+)?)pt$")


def apply_resume_theme(docx_path: Path, design_tokens: DesignTokens) -> None:
    """Update a generated DOCX with the shared site/resume visual theme.

    The editable source template remains untouched. The generated public DOCX
    receives the Word theme plus direct run and paragraph formatting, so a
    design-token edit is reflected in both its browser CSS and resume output.
    """

    colors = design_tokens.colors
    required = set(DIRECT_COLOUR_TOKENS.values()) | set(DIRECT_FILL_TOKENS.values()) | set(THEME_COLOUR_TOKENS.values())
    missing = sorted(name for name in required if name not in colors)
    if missing:
        raise ValueError(f"Resume theme is missing design token: {missing[0]}")
    required_styles = set(RESUME_TEXT_STYLE_BY_TAG.values()) | set(STATIC_RESUME_TEXT_STYLES.values())
    missing_styles = sorted(required_styles - set(design_tokens.text_styles))
    if missing_styles:
        raise ValueError(f"Resume theme is missing text style token: {missing_styles[0]}")

    modified: dict[str, bytes] = {}
    with ZipFile(docx_path) as package:
        if THEME_PART not in package.namelist():
            raise ValueError(f"Resume template is missing {THEME_PART}")

        theme_root = etree.fromstring(package.read(THEME_PART))
        _apply_theme_scheme(theme_root, colors)
        modified[THEME_PART] = etree.tostring(theme_root, encoding="UTF-8", xml_declaration=True, standalone=True)

        for part_name in package.namelist():
            if not _is_direct_formatting_part(part_name):
                continue
            root = etree.fromstring(package.read(part_name))
            changed = _apply_direct_colours(root, colors)
            if part_name == "word/document.xml":
                changed = _apply_resume_text_styles(root, design_tokens.text_styles) or changed
            if changed:
                modified[part_name] = etree.tostring(root, encoding="UTF-8", xml_declaration=True, standalone=True)

        with NamedTemporaryFile(prefix=f"{docx_path.stem}-", suffix=".docx", dir=docx_path.parent, delete=False) as handle:
            destination = Path(handle.name)
        with ZipFile(destination, "w", compression=ZIP_DEFLATED) as target:
            for info in package.infolist():
                target.writestr(info, modified.get(info.filename, package.read(info.filename)), compress_type=info.compress_type)
    try:
        destination.replace(docx_path)
    finally:
        if destination.exists():
            destination.unlink()


def _apply_theme_scheme(root: etree._Element, colors: Mapping[str, str]) -> None:
    scheme = root.find(".//a:clrScheme", namespaces=NS)
    if scheme is None:
        raise ValueError("Resume theme has no colour scheme")
    for slot_name, token_name in THEME_COLOUR_TOKENS.items():
        slot = scheme.find(f"a:{slot_name}", namespaces=NS)
        if slot is None:
            raise ValueError(f"Resume theme has no {slot_name} colour slot")
        for child in list(slot):
            slot.remove(child)
        colour = etree.SubElement(slot, f"{{{DRAWING_NS}}}srgbClr")
        colour.set("val", _word_hex(colors[token_name]))


def _apply_direct_colours(root: etree._Element, colors: Mapping[str, str]) -> bool:
    changed = False
    for colour in root.xpath(".//w:color", namespaces=NS):
        if colour.get(f"{{{WORD_NS}}}themeColor") is not None:
            continue
        value = (colour.get(f"{{{WORD_NS}}}val") or "").upper()
        token_name = DIRECT_COLOUR_TOKENS.get(value)
        if token_name:
            colour.set(f"{{{WORD_NS}}}val", _word_hex(colors[token_name]))
            changed = True
    for shading in root.xpath(".//w:shd", namespaces=NS):
        value = (shading.get(f"{{{WORD_NS}}}fill") or "").upper()
        token_name = DIRECT_FILL_TOKENS.get(value)
        if token_name:
            shading.set(f"{{{WORD_NS}}}fill", _word_hex(colors[token_name]))
            changed = True
    return changed


def _apply_resume_text_styles(root: etree._Element, text_styles: Mapping[str, TextStyle]) -> bool:
    """Apply named token styles to tagged and static resume text.

    Content controls are the stable semantic handles for editable resume copy.
    The few static labels have exact text and are intentionally styled here as
    well, so every visible text treatment comes from the token file.
    """

    changed = False
    for control in root.xpath(".//w:sdt", namespaces=NS):
        tag = control.xpath("string(w:sdtPr/w:tag/@w:val)", namespaces=NS)
        style_name = RESUME_TEXT_STYLE_BY_TAG.get(tag)
        if not style_name:
            continue
        style = text_styles[style_name]
        for run in control.xpath(".//w:sdtContent//w:r", namespaces=NS):
            _apply_text_style_to_run(run, style)
            changed = True

    for paragraph in root.xpath(".//w:p", namespaces=NS):
        if paragraph.xpath(".//w:sdt", namespaces=NS):
            continue
        text = "".join(paragraph.xpath(".//w:t/text()", namespaces=NS)).strip()
        style_name = STATIC_RESUME_TEXT_STYLES.get(text)
        if not style_name:
            continue
        style = text_styles[style_name]
        for run in paragraph.xpath(".//w:r", namespaces=NS):
            _apply_text_style_to_run(run, style)
            changed = True
    return changed


def _apply_text_style_to_run(run: etree._Element, style: TextStyle) -> None:
    properties = run.find("w:rPr", namespaces=NS)
    if properties is None:
        properties = etree.Element(f"{{{WORD_NS}}}rPr")
        run.insert(0, properties)

    font = _ensure_child(properties, "rFonts")
    family = _word_font_family(style.font_family)
    for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
        font.set(f"{{{WORD_NS}}}{attribute}", family)

    half_points = str(int(round(_point_value(style.font_size) * 2)))
    _ensure_child(properties, "sz").set(f"{{{WORD_NS}}}val", half_points)
    _ensure_child(properties, "szCs").set(f"{{{WORD_NS}}}val", half_points)
    _set_toggle(properties, "b", _is_bold(style.font_weight))
    _set_toggle(properties, "bCs", _is_bold(style.font_weight))
    _set_toggle(properties, "i", style.font_style.lower() == "italic")
    _set_toggle(properties, "iCs", style.font_style.lower() == "italic")

    colour = _ensure_child(properties, "color")
    colour.set(f"{{{WORD_NS}}}val", _word_hex(style.color))
    for attribute in ("themeColor", "themeTint", "themeShade"):
        colour.attrib.pop(f"{{{WORD_NS}}}{attribute}", None)

    tracking = _ensure_child(properties, "spacing")
    tracking.set(f"{{{WORD_NS}}}val", str(int(round(_point_value(style.letter_spacing) * 20))))
    _apply_line_height(run, style.line_height)


def _apply_line_height(run: etree._Element, line_height: str) -> None:
    paragraph = run.getparent()
    while paragraph is not None and paragraph.tag != f"{{{WORD_NS}}}p":
        paragraph = paragraph.getparent()
    if paragraph is None:
        return
    paragraph_properties = paragraph.find("w:pPr", namespaces=NS)
    if paragraph_properties is None:
        paragraph_properties = etree.Element(f"{{{WORD_NS}}}pPr")
        paragraph.insert(0, paragraph_properties)
    spacing = _ensure_child(paragraph_properties, "spacing")
    spacing.set(f"{{{WORD_NS}}}line", str(int(round(float(line_height) * 240))))
    spacing.set(f"{{{WORD_NS}}}lineRule", "auto")


def _ensure_child(parent: etree._Element, local_name: str) -> etree._Element:
    child = parent.find(f"w:{local_name}", namespaces=NS)
    if child is None:
        child = etree.SubElement(parent, f"{{{WORD_NS}}}{local_name}")
    return child


def _set_toggle(properties: etree._Element, local_name: str, enabled: bool) -> None:
    current = properties.find(f"w:{local_name}", namespaces=NS)
    if enabled and current is None:
        etree.SubElement(properties, f"{{{WORD_NS}}}{local_name}")
    elif not enabled and current is not None:
        properties.remove(current)


def _point_value(value: str) -> float:
    match = POINT_VALUE.fullmatch(value)
    if not match:
        raise ValueError(f"Resume text style values must use points; received {value!r}")
    return float(match.group(1))


def _word_font_family(value: str) -> str:
    return value.split(",", 1)[0].strip().strip('"')


def _is_bold(value: str) -> bool:
    try:
        return int(float(value)) >= 600
    except ValueError as error:
        raise ValueError(f"Resume text style fontWeight must be numeric; received {value!r}") from error


def _is_direct_formatting_part(part_name: str) -> bool:
    return part_name == "word/document.xml" or (
        part_name.startswith(("word/header", "word/footer")) and part_name.endswith(".xml")
    )


def _word_hex(value: str) -> str:
    return value.removeprefix("#").upper()
