from __future__ import annotations

import html
import json
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph


ROOT = Path(__file__).resolve().parents[1]
CONTENT_PATH = ROOT / "content" / "site.json"
INDEX_PATH = ROOT / "index.html"
STYLES_PATH = ROOT / "styles.css"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def attrs(values: dict[str, str | None]) -> str:
    rendered = [f'{key}="{esc(value)}"' for key, value in values.items() if value]
    return (" " + " ".join(rendered)) if rendered else ""


def tag_list(items: list[str], class_name: str) -> str:
    tags = "\n".join(f"                    <span>{esc(item)}</span>" for item in items)
    return f'<div class="{class_name}">\n{tags}\n                </div>'


def image_markup(image: dict | None, class_name: str) -> str:
    if not image or not image.get("src"):
        return ""
    return (
        f'                        <figure class="{class_name}">\n'
        f'                            <img src="{esc(image["src"])}" alt="{esc(image.get("alt", ""))}" loading="lazy">\n'
        f"                        </figure>\n\n"
    )


def render_index(data: dict) -> str:
    site = data["site"]
    nav = "\n".join(f'                <a href="{esc(item["href"])}">{esc(item["label"])}</a>' for item in data["nav"])
    hero_buttons = "\n\n".join(
        f'                <a href="{esc(button["href"])}" class="button {esc(button.get("style", "secondary"))}"{attrs({"target": button.get("target")})}>\n'
        f'                    {esc(button["label"])}\n'
        f"                </a>"
        for button in data["hero"]["buttons"]
    )
    experience_items = "\n\n".join(render_experience_item(item) for item in data["experience"]["items"])
    project_items = "\n\n".join(render_project_item(item) for item in data["projects"]["items"])
    photos_section = render_photos_section(data.get("photos", {}))
    passion_items = "\n\n".join(render_passion_item(item) for item in data["passions"]["items"])
    contact_links = "\n\n".join(
        f'                    <a href="{esc(link["href"])}"{attrs({"target": link.get("target")})}>\n'
        f'                        {esc(link["label"])}\n'
        f"                    </a>"
        for link in data["contact"]["links"]
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{esc(site["title"])}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <!-- Generated by scripts/build_site.py from content/site.json. -->
    <nav class="navbar">
        <div class="nav-container">
            <a href="#home" class="logo">{esc(site["initials"])}</a>

            <div class="nav-links">
{nav}
            </div>
        </div>
    </nav>

    <header class="hero" id="home">
        <div class="container hero-content">
            <p class="eyebrow">{esc(data["hero"]["eyebrow"])}</p>

            <h1>
                {esc(data["hero"]["headline_prefix"])} <span>{esc(data["hero"]["headline_name"])}</span>
            </h1>

            <p class="hero-description">
                {esc(data["hero"]["description"])}
            </p>

            <div class="hero-buttons">
{hero_buttons}
            </div>
        </div>
    </header>

    <main>
        <section class="section" id="about">
            <div class="container narrow">
                <p class="section-number">{esc(data["about"]["number"])}</p>
                <h2>{esc(data["about"]["heading"])}</h2>

                <p class="large-text">
                    {esc(data["about"]["lead"])}
                </p>

                <p>
                    {esc(data["about"]["body"])}
                </p>

                {tag_list(data["about"]["skills"], "skills")}
            </div>
        </section>

        <section class="section alternate" id="experience">
            <div class="container">
                <p class="section-number">{esc(data["experience"]["number"])}</p>
                <h2>{esc(data["experience"]["heading"])}</h2>

                <div class="timeline">
{experience_items}
                </div>

                <div class="resume-callout">
                    <div>
                        <p class="section-number">{esc(data["experience"]["callout"]["number"])}</p>
                        <h3>{esc(data["experience"]["callout"]["heading"])}</h3>
                    </div>

                    <a href="{esc(site["resume_path"])}" target="_blank" class="button primary">
                        {esc(data["experience"]["callout"]["button_label"])}
                    </a>
                </div>
            </div>
        </section>

        <section class="section" id="projects">
            <div class="container">
                <p class="section-number">{esc(data["projects"]["number"])}</p>
                <h2>{esc(data["projects"]["heading"])}</h2>

                <div class="project-grid">
{project_items}
                </div>
            </div>
        </section>

{photos_section}

        <section class="section alternate" id="passions">
            <div class="container">
                <p class="section-number">{esc(data["passions"]["number"])}</p>
                <h2>{esc(data["passions"]["heading"])}</h2>

                <div class="passion-grid">
{passion_items}
                </div>
            </div>
        </section>

        <section class="section contact-section" id="contact">
            <div class="container narrow">
                <p class="section-number">{esc(data["contact"]["number"])}</p>
                <h2>{esc(data["contact"]["heading"])}</h2>

                <p class="large-text">
                    {esc(data["contact"]["lead"])}
                </p>

                <div class="contact-links">
{contact_links}
                </div>
            </div>
        </section>
    </main>

    <footer>
        <div class="container footer-content">
            <p>&copy; {esc(site["year"])} {esc(site["name"])}</p>
            <a href="#home">Back to top ^</a>
        </div>
    </footer>
</body>
</html>
"""


def render_experience_item(item: dict) -> str:
    return f"""                    <article class="experience-item">
                        <div class="experience-date">
                            {esc(item["date"])}
                        </div>

                        <div class="experience-content">
                            <h3>{esc(item["role"])}</h3>
                            <p class="company">{esc(item["company"])}</p>

                            <p>
                                {esc(item["description"])}
                            </p>

                            {tag_list(item["tags"], "tags")}
                        </div>
                    </article>"""


def render_project_item(item: dict) -> str:
    class_name = "project-card featured" if item.get("featured") else "project-card"
    return f"""                    <article class="{class_name}">
                        <div class="project-number">{esc(item["number"])}</div>

                        <div>
{image_markup(item.get("image"), "project-image")}
                            <p class="project-type">
                                {esc(item["type"])}
                            </p>

                            <h3>{esc(item["name"])}</h3>

                            <p>
                                {esc(item["description"])}
                            </p>

                            {tag_list(item["tags"], "tags")}
                        </div>
                    </article>"""


def render_photos_section(photos: dict) -> str:
    items = photos.get("items", [])
    if not items:
        return ""
    photo_items = "\n\n".join(render_photo_item(item) for item in items)
    return f"""        <section class="section alternate" id="photos">
            <div class="container">
                <p class="section-number">{esc(photos.get("number", "PHOTOS"))}</p>
                <h2>{esc(photos.get("heading", "Photos"))}</h2>

                <p class="photo-intro">
                    {esc(photos.get("intro", ""))}
                </p>

                <div class="photo-grid">
{photo_items}
                </div>
            </div>
        </section>"""


def render_photo_item(item: dict) -> str:
    return f"""                    <figure class="photo-card">
                        <img src="{esc(item["src"])}" alt="{esc(item.get("alt", ""))}" loading="lazy">
                        <figcaption>
                            <strong>{esc(item.get("title", ""))}</strong>
                            <span>{esc(item.get("caption", ""))}</span>
                        </figcaption>
                    </figure>"""


def render_passion_item(item: dict) -> str:
    return f"""                    <div class="passion">
                        <span class="passion-number">{esc(item["number"])}</span>
                        <h3>{esc(item["name"])}</h3>
                        <p>
                            {esc(item["description"])}
                        </p>
                    </div>"""


def render_styles() -> str:
    return """/* Generated by scripts/build_site.py from content/site.json. */

:root {
    --background: #f4f2ed;
    --surface: #e9e6df;
    --text: #151515;
    --muted: #676767;
    --border: #c9c5bc;
    --accent: #e94f2f;
    --accent-dark: #c73b20;
    --max-width: 1180px;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

html {
    scroll-behavior: smooth;
}

body {
    font-family: Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
    background: var(--background);
    color: var(--text);
    line-height: 1.6;
}

a {
    color: inherit;
    text-decoration: none;
}

.container {
    width: min(90%, var(--max-width));
    margin: 0 auto;
}

.narrow {
    max-width: 850px;
}

.section {
    padding: 120px 0;
}

.alternate {
    background: var(--surface);
}

.section-number {
    font-size: 0.75rem;
    letter-spacing: 0.16em;
    font-weight: 700;
    color: var(--accent);
    margin-bottom: 18px;
}

h1,
h2,
h3 {
    line-height: 1.08;
}

h2 {
    font-size: clamp(2.6rem, 6vw, 5rem);
    letter-spacing: -0.05em;
    margin-bottom: 50px;
}

h3 {
    font-size: 1.6rem;
}

p {
    color: var(--muted);
}

.large-text {
    font-size: clamp(1.35rem, 2.5vw, 2rem);
    color: var(--text);
    line-height: 1.45;
    margin-bottom: 25px;
}

.navbar {
    position: sticky;
    top: 0;
    z-index: 100;
    background: rgba(244, 242, 237, 0.92);
    backdrop-filter: blur(10px);
    border-bottom: 1px solid var(--border);
}

.nav-container {
    width: min(90%, var(--max-width));
    height: 72px;
    margin: 0 auto;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.logo {
    font-size: 1.4rem;
    font-weight: 800;
}

.nav-links {
    display: flex;
    gap: 30px;
    font-size: 0.9rem;
    font-weight: 600;
}

.nav-links a {
    transition: color 0.2s;
}

.nav-links a:hover {
    color: var(--accent);
}

.hero {
    min-height: calc(100vh - 72px);
    display: flex;
    align-items: center;
    padding: 80px 0;
}

.hero-content {
    max-width: var(--max-width);
}

.eyebrow {
    color: var(--accent);
    letter-spacing: 0.18em;
    font-size: 0.8rem;
    font-weight: 700;
    margin-bottom: 25px;
}

.hero h1 {
    font-size: clamp(4rem, 10vw, 9rem);
    letter-spacing: -0.07em;
    max-width: 1000px;
}

.hero h1 span {
    color: var(--accent);
}

.hero-description {
    max-width: 680px;
    font-size: clamp(1.1rem, 2vw, 1.45rem);
    margin-top: 35px;
}

.hero-buttons {
    display: flex;
    gap: 15px;
    flex-wrap: wrap;
    margin-top: 40px;
}

.button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 13px 22px;
    border: 1px solid var(--text);
    font-weight: 700;
    font-size: 0.9rem;
    transition: 0.2s ease;
}

.button.primary {
    background: var(--text);
    color: white;
}

.button.primary:hover {
    background: var(--accent);
    border-color: var(--accent);
}

.button.secondary:hover {
    background: var(--text);
    color: white;
}

.skills,
.tags {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
}

.skills {
    margin-top: 35px;
}

.skills span,
.tags span {
    border: 1px solid var(--border);
    padding: 6px 11px;
    font-size: 0.8rem;
    font-weight: 600;
}

.timeline {
    border-top: 1px solid var(--border);
}

.experience-item {
    display: grid;
    grid-template-columns: 200px 1fr;
    gap: 60px;
    padding: 45px 0;
    border-bottom: 1px solid var(--border);
}

.experience-date {
    color: var(--muted);
    font-family: monospace;
    font-size: 0.85rem;
}

.experience-content {
    max-width: 700px;
}

.company {
    color: var(--accent);
    font-weight: 600;
    margin: 5px 0 18px;
}

.experience-content .tags {
    margin-top: 20px;
}

.resume-callout {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 30px;
    margin-top: 80px;
    padding: 35px;
    border: 1px solid var(--border);
}

.resume-callout .section-number {
    margin-bottom: 6px;
}

.project-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 15px;
}

.project-card {
    min-height: 350px;
    border: 1px solid var(--border);
    padding: 30px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    transition: transform 0.2s, border-color 0.2s;
}

.project-card:hover {
    transform: translateY(-5px);
    border-color: var(--accent);
}

.project-card.featured {
    grid-column: span 2;
    min-height: 430px;
}

.project-number {
    font-family: monospace;
    color: var(--accent);
    margin-bottom: 80px;
}

.project-type {
    font-size: 0.7rem;
    font-weight: 700;
    letter-spacing: 0.15em;
    margin-bottom: 8px;
}

.project-card h3 {
    font-size: clamp(1.8rem, 3vw, 2.6rem);
    margin-bottom: 15px;
}

.project-card p {
    max-width: 600px;
}

.project-card .tags {
    margin-top: 25px;
}

.project-image {
    aspect-ratio: 16 / 10;
    margin-bottom: 28px;
    overflow: hidden;
    border: 1px solid var(--border);
    background: var(--surface);
}

.project-image img,
.photo-card img {
    display: block;
    width: 100%;
    height: 100%;
    object-fit: cover;
}

.photo-intro {
    max-width: 700px;
    margin-top: -25px;
    margin-bottom: 35px;
    font-size: 1.05rem;
}

.photo-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 15px;
}

.photo-card {
    border: 1px solid var(--border);
    background: var(--background);
}

.photo-card img {
    aspect-ratio: 4 / 3;
}

.photo-card figcaption {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 16px;
}

.photo-card strong {
    line-height: 1.2;
}

.photo-card span {
    color: var(--muted);
    font-size: 0.9rem;
}

.passion-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    border-top: 1px solid var(--border);
}

.passion {
    padding: 40px;
    min-height: 260px;
    border-right: 1px solid var(--border);
    border-bottom: 1px solid var(--border);
}

.passion:nth-child(even) {
    border-right: none;
}

.passion-number {
    display: block;
    font-family: monospace;
    color: var(--accent);
    margin-bottom: 45px;
}

.passion h3 {
    margin-bottom: 15px;
}

.contact-section {
    min-height: 70vh;
    display: flex;
    align-items: center;
}

.contact-links {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
    margin-top: 40px;
}

.contact-links a {
    font-size: 1.2rem;
    font-weight: 700;
    border-bottom: 1px solid var(--text);
    transition: color 0.2s;
}

.contact-links a:hover {
    color: var(--accent);
}

footer {
    border-top: 1px solid var(--border);
    padding: 30px 0;
}

.footer-content {
    display: flex;
    justify-content: space-between;
    font-size: 0.85rem;
}

@media (max-width: 800px) {
    .section {
        padding: 80px 0;
    }

    .nav-links {
        display: none;
    }

    .hero {
        min-height: 85vh;
    }

    .experience-item {
        grid-template-columns: 1fr;
        gap: 15px;
    }

    .project-grid {
        grid-template-columns: 1fr;
    }

    .project-card.featured {
        grid-column: span 1;
    }

    .photo-grid {
        grid-template-columns: 1fr;
    }

    .passion-grid {
        grid-template-columns: 1fr;
    }

    .passion {
        border-right: none;
    }

    .resume-callout {
        flex-direction: column;
        align-items: flex-start;
    }

    .footer-content {
        flex-direction: column;
        gap: 8px;
    }
}
"""


def build_pdf(data: dict, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    resume = data.get("resume")
    if not resume:
        raise ValueError("content/site.json must include a resume block")
    if len(resume.get("pages", [])) > 2:
        raise ValueError("Resume template supports a maximum of two pages")

    renderer = ResumeRenderer(output_path)
    renderer.draw(resume)


class ResumeRenderer:
    def __init__(self, output_path: Path) -> None:
        self.output_path = output_path
        self.width, self.height = LETTER
        self.margin_x = 0.58 * inch
        self.top = self.height - 0.52 * inch
        self.bottom = 0.5 * inch
        self.content_width = self.width - (2 * self.margin_x)
        self.canvas = canvas.Canvas(str(output_path), pagesize=LETTER)
        self.styles = {
            "headline": ParagraphStyle(
                "headline",
                fontName="Helvetica",
                fontSize=9,
                leading=11,
                textColor=colors.HexColor("#555555"),
            ),
            "body": ParagraphStyle(
                "body",
                fontName="Helvetica",
                fontSize=8.7,
                leading=10.5,
                textColor=colors.HexColor("#222222"),
            ),
            "bullet": ParagraphStyle(
                "bullet",
                fontName="Helvetica",
                fontSize=8.5,
                leading=10.2,
                leftIndent=10,
                bulletIndent=0,
                textColor=colors.HexColor("#222222"),
            ),
        }

    def draw(self, resume: dict) -> None:
        pages = resume.get("pages", [])
        for page_index in range(2):
            page = pages[page_index] if page_index < len(pages) else {"title": "", "blocks": []}
            self._draw_page(resume, page, page_index + 1)
            if page_index == 0:
                self.canvas.showPage()
        self.canvas.save()

    def _draw_page(self, resume: dict, page: dict, page_number: int) -> None:
        c = self.canvas
        y = self.top

        c.setFillColor(colors.HexColor("#151515"))
        c.setFont("Helvetica-Bold", 20)
        c.drawString(self.margin_x, y, str(resume.get("name", "[insert name]")))
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#555555"))
        c.drawRightString(self.width - self.margin_x, y + 1, f"Page {page_number} of 2")
        y -= 16

        y = self._draw_paragraph(str(resume.get("headline", "")), y, "headline", page_number, gap=5)
        contact = "  |  ".join(str(item) for item in resume.get("contact", []) if item)
        y = self._draw_paragraph(contact, y, "headline", page_number, gap=12)

        c.setStrokeColor(colors.HexColor("#e94f2f"))
        c.setLineWidth(1.3)
        c.line(self.margin_x, y, self.width - self.margin_x, y)
        y -= 14

        if page.get("title"):
            c.setFont("Helvetica-Bold", 8.5)
            c.setFillColor(colors.HexColor("#e94f2f"))
            c.drawString(self.margin_x, y, str(page["title"]).upper())
            y -= 18

        for block in page.get("blocks", []):
            y = self._draw_block(block, y, page_number)

        c.setStrokeColor(colors.HexColor("#c9c5bc"))
        c.setLineWidth(0.6)
        c.line(self.margin_x, self.bottom - 5, self.width - self.margin_x, self.bottom - 5)

    def _draw_block(self, block: dict, y: float, page_number: int) -> float:
        block_type = block.get("type", "section")
        y = self._draw_heading(str(block.get("heading", "[insert section heading]")), y, page_number)
        if block_type == "skills":
            for group in block.get("groups", []):
                label = html.escape(str(group.get("label", "[insert skill group]")), quote=False)
                items = html.escape(", ".join(str(item) for item in group.get("items", [])), quote=False)
                text = f"<b>{label}:</b> {items}"
                y = self._draw_paragraph(text, y, "body", page_number, gap=4, allow_markup=True)
            return y - 7

        for item in block.get("items", []):
            y = self._draw_resume_item(item, y, page_number)
        return y - 4

    def _draw_heading(self, heading: str, y: float, page_number: int) -> float:
        y = self._ensure_space(y, 22, page_number)
        self.canvas.setFillColor(colors.HexColor("#151515"))
        self.canvas.setFont("Helvetica-Bold", 10.5)
        self.canvas.drawString(self.margin_x, y, heading.upper())
        self.canvas.setStrokeColor(colors.HexColor("#c9c5bc"))
        self.canvas.setLineWidth(0.5)
        self.canvas.line(self.margin_x, y - 4, self.width - self.margin_x, y - 4)
        return y - 16

    def _draw_resume_item(self, item: dict, y: float, page_number: int) -> float:
        title = str(item.get("role", "[insert role or project title]"))
        org = str(item.get("organization", "[insert organization]"))
        location = str(item.get("location", ""))
        dates = str(item.get("dates", "[insert dates]"))
        meta = " | ".join(part for part in [org, location] if part)

        y = self._ensure_space(y, 36, page_number)
        self.canvas.setFillColor(colors.HexColor("#151515"))
        self.canvas.setFont("Helvetica-Bold", 9.4)
        self.canvas.drawString(self.margin_x, y, title)
        self.canvas.setFont("Helvetica", 8.4)
        self.canvas.setFillColor(colors.HexColor("#555555"))
        self.canvas.drawRightString(self.width - self.margin_x, y, dates)
        y -= 10

        y = self._draw_paragraph(meta, y, "headline", page_number, gap=4)
        for bullet in item.get("bullets", []):
            y = self._draw_paragraph(str(bullet), y, "bullet", page_number, gap=2, bullet_text="-")
        return y - 6

    def _draw_paragraph(
        self,
        text: str,
        y: float,
        style_name: str,
        page_number: int,
        gap: float = 4,
        bullet_text: str | None = None,
        allow_markup: bool = False,
    ) -> float:
        if not text:
            return y
        paragraph_text = text if allow_markup else html.escape(text, quote=False)
        paragraph = Paragraph(paragraph_text, self.styles[style_name], bulletText=bullet_text)
        _, height = paragraph.wrap(self.content_width, y - self.bottom)
        y = self._ensure_space(y, height + gap, page_number)
        paragraph.drawOn(self.canvas, self.margin_x, y - height)
        return y - height - gap

    def _ensure_space(self, y: float, needed: float, page_number: int) -> float:
        if y - needed < self.bottom:
            raise RuntimeError(
                f"Resume page {page_number} overflowed. Shorten blocks in content/site.json to keep the resume at two pages."
            )
        return y


def main() -> None:
    data = json.loads(CONTENT_PATH.read_text(encoding="utf-8"))
    INDEX_PATH.write_text(render_index(data), encoding="utf-8", newline="\n")
    STYLES_PATH.write_text(render_styles(), encoding="utf-8", newline="\n")
    build_pdf(data, ROOT / data["site"]["resume_path"])
    print(f"Built {INDEX_PATH.relative_to(ROOT)}, {STYLES_PATH.relative_to(ROOT)}, and {data['site']['resume_path']}")


if __name__ == "__main__":
    main()
